amcl_3d:
  ros__parameters:
    map_frame_id: map
    base_link_frame_id: base_link
    odom_frame_id: odom
    publish_rate: 10.0
    amcl_param:
      augmented_mcl:
        alpha_fast: 0.95
        alpha_slow: 0.05
        w_fast: 0.5
        w_slow: 0.5
        noise_x_var: 1.0
        noise_y_var: 1.0
        noise_z_var: 0.2
        noise_roll_var: 0.1
        noise_pitch_var: 0.1
        noise_yaw_var: 0.1
      init_pose:
        initial_particle_num: 100
      resample_timing:
        ess_ratio_threshold: 0.7
      kld_sampling:
        min_particle_num: 100
        max_particle_num: 2000
        delta: 0.5
        epsilon: 0.5
        x_bin_width: 0.2
        y_bin_width: 0.2
        z_bin_width: 0.2
