name: Jazzy CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-latest

    steps:
      - name: Build workspace
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: amcl_3d
          target-ros2-distro: jazzy
          import-token: ${{ secrets.GITHUB_TOKEN }}
          skip-tests: false
          coverage-result: false
